### ISSUE TITLE
error on install / dev command

### ISSUE THREAD

**Issue by cball** [echobind/bisonapp#48] opened 2020-09-02 14:26 UTC
In https://lelon.io/blog/getting-started-with-bison, Joshua got an error on install:

![image](https://user-images.githubusercontent.com/14339/91995620-09e7e300-ed06-11ea-969a-a0db8889baf1.png)

When trying to run `yarn dev`, he got this:
![image](https://user-images.githubusercontent.com/14339/91995691-1e2be000-ed06-11ea-9c70-2f6b4f67f44c.png)

I can't reproduce this immediately, but it looks like there might be some module resolution issues with chokidar/next.

**Comment by kgajera** [comment] 2021-11-05 16:46
Because this is over a year old and not reproducible, I'm going to close this.

**Closed by kgajera** 2021-11-05 16:46 UTC
Labels: bug
